title:              Devlog - 데블로그
email:              pjh4564@nate.com
description:        Devlog - 개발일지
author:             Jean
baseurl:            "/"
url:                "https://JinhwanPark.github.io"

# Social Profiles
twitter_username:   x
github_username:    JinhwanPark
facebook_username:  JinhwanPark
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-177782736-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
